//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Buongustaio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [Key]
        [Required]
        public string Folio { get; set; }
        public string Comprobante { get; set; }
        public string RFC { get; set; }
    
        public virtual Comprobantes Comprobantes { get; set; }
        public virtual DatosFiscales DatosFiscales { get; set; }
    }
}
