//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buongustaio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredientes
    {
        public string Id { get; set; }
        public string Lote { get; set; }
        public string Ingrediente { get; set; }
        public double Cantidad { get; set; }
        public System.DateTime Fecha_Compra { get; set; }
        public System.DateTime Fecha_Expiracion { get; set; }
    }
}
