
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Buongustaio.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Miembros
{

    public string Estatus { get; set; }

    public System.DateTime Expiracion { get; set; }

    public string Id { get; set; }

    public decimal cliente { get; set; }



    public virtual Clientes Clientes { get; set; }

}

}
