
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Buongustaio.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ordenes
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ordenes()
    {

        this.Comprobantes = new HashSet<Comprobantes>();

    }


    public string Id { get; set; }

    public decimal Cliente { get; set; }

    public string Pedido { get; set; }

    public System.DateTime Fecha { get; set; }



    public virtual Clientes Clientes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Comprobantes> Comprobantes { get; set; }

}

}
