//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buongustaio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pagos()
        {
            this.Comprobantes = new HashSet<Comprobantes>();
        }
    
        public string Id { get; set; }
        public string NumTarjeta { get; set; }
        public string Expiracion { get; set; }
        public string Propietario { get; set; }
        public decimal Clave { get; set; }
        public double Cantidad { get; set; }
        public string Transaccion { get; set; }
        public string Pedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comprobantes> Comprobantes { get; set; }
        public virtual Pedidos Pedidos { get; set; }
    }
}
