//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buongustaio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string Id { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public string Ingredientes { get; set; }
        public string Imagen { get; set; }
        public Nullable<double> Descuento { get; set; }
    }
}
