//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buongustaio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string Id { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public string Ingredientes { get; set; }
        public string Imagen { get; set; }
        public Nullable<double> Descuento { get; set; }
    }
}
